### ISSUE TITLE
Could not pass event ShopPreTransactionEvent

### ISSUE THREAD

**Issue by Strahilchu** [Auxilor/EcoSkills#109]
[01:36:18 ERROR]: Could not pass event ShopPreTransactionEvent to eco v6.38.2
java.lang.NoSuchMethodError: 'net.brcdev.shopgui.shop.item.ShopItem net.brcdev.shopgui.event.ShopPreTransactionEvent.getShopItem()'
        at com.willfp.eco.internal.spigot.integrations.shop.ShopShopGuiPlus$ShopGuiPlusSellEventListeners.shopEventToEcoEvent(ShopShopGuiPlus.kt:53) ~[eco-6.38.2-all.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor68.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[petal-api-1.19.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[petal-api-1.19.1-R0.1-SNAPSHOT.jar:git-petal-"8ba3e6e"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[petal-api-1.19.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:678) ~[petal-api-1.19.1-R0.1-SNAPSHOT.jar:?]
        at net.brcdev.shopgui.shop.ShopManager.handleItemSellAll(ShopManager.java:1142) ~[ShopGUIPlus-1.77.3.jar:?]
        at net.brcdev.shopgui.listener.PlayerListener.clickAmountSelectionGui(PlayerListener.java:420) ~[ShopGUIPlus-1.77.3.jar:?]
        at net.brcdev.shopgui.listener.PlayerListener.onInventoryClick(PlayerListener.java:139) ~[ShopGUIPlus-1.77.3.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor718.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[petal-api-1.19.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[petal-api-1.19.1-R0.1-SNAPSHOT.jar:git-petal-"8ba3e6e"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[petal-api-1.19.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:678) ~[petal-api-1.19.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3369) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[petal-1.19.1.jar:git-petal-"8ba3e6e"]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1386) ~[petal-1.19.1.jar:git-petal-"8ba3e6e"]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[petal-1.19.1.jar:git-petal-"8ba3e6e"]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1363) ~[petal-1.19.1.jar:git-petal-"8ba3e6e"]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1356) ~[petal-1.19.1.jar:git-petal-"8ba3e6e"]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1334) ~[petal-1.19.1.jar:git-petal-"8ba3e6e"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1222) ~[petal-1.19.1.jar:git-petal-"8ba3e6e"]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[petal-1.19.1.jar:git-petal-"8ba3e6e"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Strahilchu** [comment]
Can this be fixed? What does this plugin have to do with my GuiShop at all?

**Comment by TomTeDev** [comment]
> 

Plugin author is on vacations https://discord.com/channels/452518336627081236/718515639253205043/1005911839944740875

**Comment by Strahilchu** [comment]
Updates are releasing but stuff not being fixed

**Comment by WillFP** [comment]
Update your ShopGUIPlus
