### ISSUE TITLE
java.lang.NoClassDefFoundError: com/willfp/ecoskills/effects/CustomEffects

### ISSUE THREAD

**Issue by TomTeDev** [Auxilor/EcoSkills#110]
Server version: Current: git-Purpur-1632 (MC: 1.18.2)*
Ecoskills version 1.65.0
Eco version 6.38.2

[15:40:02 ERROR]: Error occurred while disabling EcoSkills v1.65.0 (Is it up to date?)
java.lang.NoClassDefFoundError: com/willfp/ecoskills/effects/CustomEffects
        at com.willfp.ecoskills.effects.CustomEffectUtils.getCustomEffects(CustomEffect.kt:89) ~[EcoSkills v1.65.0.jar:?]
        at com.willfp.ecoskills.libreforge.LibReforgePlugin$registerJavaHolderProvider$1.invoke(LibReforge.kt:86) ~[EcoSkills v1.65.0.jar:?]
        at com.willfp.ecoskills.libreforge.LibReforgePlugin$registerJavaHolderProvider$1.invoke(LibReforge.kt:86) ~[EcoSkills v1.65.0.jar:?]
        at com.willfp.ecoskills.libreforge.LibReforgeUtils.getPureHolders$lambda-1(LibReforge.kt:186) ~[EcoSkills v1.65.0.jar:?]
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$13(BoundedLocalCache.java:2550) ~[eco-6.38.2-all.jar:?]
        at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1916) ~[?:?]
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2548) ~[eco-6.38.2-all.jar:?]
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2531) ~[eco-6.38.2-all.jar:?]
        at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:110) ~[eco-6.38.2-all.jar:?]
        at com.github.benmanes.caffeine.cache.LocalManualCache.get(LocalManualCache.java:62) ~[eco-6.38.2-all.jar:?]
        at com.willfp.ecoskills.libreforge.LibReforgeUtils.getPureHolders(LibReforge.kt:185) ~[EcoSkills v1.65.0.jar:?]
        at com.willfp.ecoskills.libreforge.LibReforgeUtils.getHolders(LibReforge.kt:197) ~[EcoSkills v1.65.0.jar:?]
        at com.willfp.ecoskills.libreforge.LibReforgeUtils.getActiveEffects(LibReforge.kt:201) ~[EcoSkills v1.65.0.jar:?]
        at com.willfp.ecoskills.libreforge.LibReforgePlugin.handleDisable(LibReforge.kt:119) ~[EcoSkills v1.65.0.jar:?]
        at com.willfp.eco.core.EcoPlugin.onDisable(EcoPlugin.java:429) ~[eco-6.38.2-all.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:401) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:578) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:376) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at com.rylinaux.plugman.util.PluginUtil.enable(PluginUtil.java:69) ~[PlugManX (2).jar:?]
        at com.rylinaux.plugman.command.EnableCommand.execute(EnableCommand.java:127) ~[PlugManX (2).jar:?]
        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) ~[PlugManX (2).jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:906) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2390) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2201) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2182) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1427) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1404) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1397) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1375) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1257) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by 0ft3n** [comment]
> 

Corrupted jar, redownload
