### ISSUE TITLE
Could not pass event PlayerFishEvent to EcoSkills v1.20.23 IllegalArgumentException

### ISSUE THREAD

**Issue by Pan1sT** [Auxilor/EcoSkills#52]
[05:31:37 ERROR]: Could not pass event PlayerFishEvent to EcoSkills v1.20.23
java.lang.IllegalArgumentException: bound must be greater than origin
        at jdk.internal.util.random.RandomSupport.checkRange(RandomSupport.java:232) ~[?:?]
        at java.util.random.RandomGenerator.nextInt(RandomGenerator.java:679) ~[?:?]
        at java.util.concurrent.ThreadLocalRandom.nextInt(ThreadLocalRandom.java:458) ~[?:?]
        at com.willfp.eco.util.NumberUtils.randInt(NumberUtils.java:164) ~[eco-6.25.2-all.jar:?]
        at com.willfp.ecoskills.effects.effects.EffectEyeOfTheDepths.handle(EffectEyeOfTheDepths.kt:45) ~[EcoSkills v1.20.23.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1212.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[pufferfish-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[pufferfish-api-1.18.1-R0.1-SNAPSHOT.jar:git-Pufferfish-47]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[pufferfish-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:631) ~[pufferfish-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.world.entity.projectile.FishingHook.retrieve(FishingHook.java:509) ~[?:?]
        at net.minecraft.world.item.FishingRodItem.use(FishingRodItem.java:30) ~[?:?]
        at net.minecraft.world.item.ItemStack.use(ItemStack.java:475) ~[pufferfish-1.18.1.jar:git-Pufferfish-47]
        at net.minecraft.server.level.ServerPlayerGameMode.useItem(ServerPlayerGameMode.java:492) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItem(ServerGamePacketListenerImpl.java:1914) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemPacket.handle(ServerboundUseItemPacket.java:28) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemPacket.a(ServerboundUseItemPacket.java:8) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[pufferfish-1.18.1.jar:git-Pufferfish-47]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1416) ~[pufferfish-1.18.1.jar:git-Pufferfish-47]
        at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[pufferfish-1.18.1.jar:git-Pufferfish-47]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1393) ~[pufferfish-1.18.1.jar:git-Pufferfish-47]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1386) ~[pufferfish-1.18.1.jar:git-Pufferfish-47]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1364) ~[pufferfish-1.18.1.jar:git-Pufferfish-47]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1270) ~[pufferfish-1.18.1.jar:git-Pufferfish-47]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:319) ~[pufferfish-1.18.1.jar:git-Pufferfish-47]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by WillFP** [comment]
Fixed in latest
